#%RAML 1.0 NamedExample
exampleTokenResponse:
  {
    "access_token": "ST47Gk5H9tbtMmYFki0u88wrI9AA",
    "token_type": "Bearer",
    "expires_in": 1449,
    "issued_at": "1748953463245",
    "scope": "https://api.equifax.com/business/id-report/v1 https://api.equifax.com/business/amlc/v1/entity-screenings"
}