#%RAML 1.0 NamedExample
  request-example:
    {
    "consumers": { 
        "name": [{
            "identifier": "current",
            "firstName": "LJBKFJ",
            "lastName": "KHJGUFJM"
        }],
        "socialNum": [{
            "identifier": "current",
            "number": "666123456"
        }],
        "addresses": [{
            "identifier": "current",
            "houseNumber": "123",
            "streetName": "POIBHHFJD",
            "streetType": "ST",
            "city": "ATLANTA",
            "state": "GA",
            "zip": "30374"
        }]
      },
    "customerReferenceIdentifier": "2C800002-DOR7",
    "customerConfiguration": {
      "equifaxIDReport": {
        "memberNumber": "999XX12345",
        "securityCode": "@U2",
        "customerCode": "IAPI",
        "multipleReportIndicator": "1",
        "ECOAInquiryType": "Individual",
        "endUserInformation": {
          "endUsersName": "jsontest",
          "permissiblePurposeCode": "30"
        }
      }
    }
}